# Air configuration file
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ./cmd/server"
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "./tmp/main"
# Watch these directories for changes
include_dir = ["cmd", "internal", "pkg"]
# Exclude files/directories
exclude_dir = ["tmp", "vendor"]
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these files
exclude_file = []

[log]
# Show log time
time = true

[color]
# Customize each log part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true
keep_scroll = true
